### ISSUE TITLE
Pre Shared Key not sticking when editing

### ISSUE THREAD

**Issue by NordloSydost-Pajje** [robertlynch3/netbox-tunnels2#4]
**NetBox version**
What version of NetBox are you currently running? 
3.5.1

**Describe the bug**
When i edit an existing tunnel the Pre Shared Key does not remain. When the tunnel dispalys after edit the Pre Shared Key field is empty.

**To Reproduce**
1. Go to 'Tunnels'
2. Click on 'Edit'
3. Save
4. Display Tunnel

**Expected behavior**
The Pre Shared Key should remain as entered when created tunnel.

Alsow i would expect the preshared key be obfuscated whit a button to show Pre Shared key beside it. Security consern.

**Screenshots**

**Additional context**
![RemoteDesktopManagerFree_l
![RemoteDesktopManagerFree_5TdCPut2nA](https://user-images.githubusercontent.com/49557334/236637479-c31564a5-235d-4818-8233-b6380200a175.png)
r0Y7aWfC5](https://user-images.githubusercontent.com/49557334/236637473-c5786157-f9d9-49cd-9332-e632fb6684a8.png)
![RemoteDesktopManagerFree_2vImzOsPlC](https://user-images.githubusercontent.com/49557334/236637492-daa34ed8-9cc3-47cb-b91c-cb4e66b200ff.png)

**Comment by robertlynch3** [comment]
I believe this has to do with the fact that the PSK is using the password widget.
https://github.com/robertlynch3/netbox-tunnels2/blob/c85c5d1f0e9ec2f946419f73e4cb1339447021d3/netbox_tunnels2/forms.py#L59

I don't believe the password widget is even necessary though because the PSK saved in plaintext and is displayed in plaintext when you look at the tunnel info.

**Comment by NordloSydost-Pajje** [comment]
I removed the password widget and now i works as expected!

Thanx!

**Comment by robertlynch3** [comment]
I am reopening because it's still an issue.
